export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  dashboard: '/app',
  aiAssistant: '/app/ai-assistant',
  assessment: '/app/assessment',
  insights: '/app/insights',
  pastInsights: '/app/insights/past',
  family: '/app/family',
  familyEdit: '/app/family/:id/edit',
  health: '/app/health',
  doctors: '/app/doctors',
  doctorsAdd: '/app/doctors/add',
  doctorsEdit: '/app/doctors/:id/edit',
  medicines: '/app/medicines',
  medicinesAdd: '/app/medicines/add',
  medicinesEdit: '/app/medicines/:id/edit',
  checkupsAdd: '/app/checkups/add',
  checkupsEdit: '/app/checkups/:id/edit',
  reports: '/app/reports',
  reportsUpload: '/app/reports/upload',
  reportsEdit: '/app/reports/:id/edit',
  generateReport: '/app/generate-report',
  education: '/app/education',
  settings: '/app/settings',
};
